apiVersion: v1
kind: Pod
metadata:
  name: pumba
spec:
  containers:
  - name: pumba
    image: gaiaadm/pumba
    command: [ "pumba", "kill", "--random", "--interval", "20s", "re2:.*backend.*" ]
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
