apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: "https://github.com/your-org/backend-repo.git"
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
