apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flappy-backend
  template:
    metadata:
      labels:
        app: flappy-backend
    spec:
      containers:
      - name: backend
        image: laumih/flappy-backend:v1
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
